"""Tests for the four synthetic scenarios in fixtures/scenarios/.

Generated by `python3 scripts/build_scenarios.py`. The scenarios mutate the supplied
gold workbook to exercise distinct reconciliation patterns:

  1. clean_match           — every row ties (composite bridges net to 0)
  2. amount_diffs          — clean baseline + known Internal mutations producing 2 diffs
  3. new_stripe_rc         — clean baseline + an unmapped Stripe rc
  4. new_internal_rc       — clean baseline + an unmapped Internal rc

These tests load the live mapping but filter it down to a frozen baseline of rcs so
user edits to config/mapping.yaml (e.g. mapping the scenario-3 test rc) don't break
the scenario assertions.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from threshold import pipeline
from threshold.config import Mapping

SCENARIOS_DIR = Path(__file__).parent.parent / "fixtures" / "scenarios"

SCENARIO_FILES = {
    "clean_match": SCENARIOS_DIR / "scenario_1_clean_match.xlsx",
    "amount_diffs": SCENARIOS_DIR / "scenario_2_amount_diffs.xlsx",
    "new_stripe_rc": SCENARIOS_DIR / "scenario_3_new_stripe_rc.xlsx",
    "new_internal_rc": SCENARIOS_DIR / "scenario_4_new_internal_rc.xlsx",
}

# The 21 rcs that ship in the bundled baseline mapping. Any user-added rc (e.g. when
# resolving an unmapped exception via the Mapping Editor) is filtered out so scenario
# 3 / 4 tests still see the expected unmapped behaviour.
BASELINE_RCS = {
    "charge", "refund", "refund_failure", "dispute_gross", "dispute_reversal_gross", "network_cost",
    "dispute_fee", "dispute_reversal_fee", "fee",
    "transfer", "transfer_reversal", "connect_collection_transfer",
    "platform_earning", "platform_earning_refund", "revenue_share",
    "dispute", "dispute_reversal",
    "other_adjustment",
    "payout_minimum_balance_hold", "payout_minimum_balance_release",
    "subscription_tax",
}


def _baseline_mapping() -> Mapping:
    """Load the live mapping but restrict to baseline rcs only."""
    m = Mapping.load()
    m.rc_rules = {rc: r for rc, r in m.rc_rules.items() if rc in BASELINE_RCS}
    return m


def _run(path: Path):
    mapping = _baseline_mapping()
    with open(path, "rb") as f:
        data = f.read()
    return pipeline.run(data, data, mapping)


@pytest.fixture(scope="module")
def clean():
    return _run(SCENARIO_FILES["clean_match"])


@pytest.fixture(scope="module")
def diffs():
    return _run(SCENARIO_FILES["amount_diffs"])


@pytest.fixture(scope="module")
def new_stripe():
    return _run(SCENARIO_FILES["new_stripe_rc"])


@pytest.fixture(scope="module")
def new_internal():
    return _run(SCENARIO_FILES["new_internal_rc"])


# --- Scenario 1: clean_match -------------------------------------------------

class TestScenario1CleanMatch:
    def test_period_detected(self, clean):
        assert clean.source.period_label == "2026-01"

    def test_grand_residual_is_zero(self, clean):
        # Composite bridges net to 0 across components + parent rows.
        assert abs(clean.summary.grand_residual) < 1.0

    def test_no_sign_anomalies(self, clean):
        assert all("SIGN ANOMALY" not in (e.suggested_tag or "") for e in clean.exceptions)

    def test_no_true_reconciling_items(self, clean):
        causes = {e.cause for e in clean.exceptions}
        assert "stripe_only" not in causes
        assert "internal_only" not in causes
        assert "reserve_pair" not in causes
        assert "unclassified" not in causes
        assert "unmapped_stripe" not in causes
        assert "unmapped_internal" not in causes

    def test_only_composite_exceptions(self, clean):
        # Every exception should be a composite component or parent (the bridges).
        composite_causes = {"composite_internal_split", "composite_stripe_parent"}
        assert all(e.cause in composite_causes for e in clean.exceptions)

    def test_composite_bridges_sum_to_zero(self, clean):
        for bridge in clean.summary.composite_bridges:
            # Last row of each bridge is the Δ (Sum − Stripe NET) row.
            delta = bridge.iloc[-1]["Amount"]
            assert abs(delta) < 1.0

    def test_no_unmapped_rcs(self, clean):
        assert clean.recon.unmapped_stripe_rcs == []
        assert clean.recon.unmapped_internal_rcs == []

    def test_per_cat_validation_ties(self, clean):
        mapping = _baseline_mapping()
        delta = (clean.rows[mapping.cat_columns].sum() - clean.recon.cat_validation).abs().max()
        assert delta < 1.0


# --- Scenario 2: amount_diffs ------------------------------------------------

class TestScenario2AmountDiffs:
    def test_period_detected(self, diffs):
        assert diffs.source.period_label == "2026-02"

    def test_known_refund_variance(self, diffs):
        # billing/refund bumped +5,000 → row 1.2 variance = +5,000
        row = diffs.rows[diffs.rows["Ref"] == 1.2].iloc[0]
        assert row["Variance"] == pytest.approx(5000.0, abs=1.0)
        assert row["Tie?"] == "✗"

    def test_known_transfer_variance(self, diffs):
        # cx_transfer/transfer reduced -1,500 → row 3.1 variance = -1,500
        row = diffs.rows[diffs.rows["Ref"] == 3.1].iloc[0]
        assert row["Variance"] == pytest.approx(-1500.0, abs=1.0)
        assert row["Tie?"] == "✗"

    def test_diffs_classified_as_unexplained(self, diffs):
        unexplained = {e.ref: e.variance for e in diffs.exceptions if e.cause == "unclassified"}
        assert 1.2 in unexplained and unexplained[1.2] == pytest.approx(5000.0, abs=1.0)
        assert 3.1 in unexplained and unexplained[3.1] == pytest.approx(-1500.0, abs=1.0)

    def test_no_unmapped_rcs(self, diffs):
        assert diffs.recon.unmapped_stripe_rcs == []
        assert diffs.recon.unmapped_internal_rcs == []

    def test_residual_equals_sum_of_known_diffs(self, diffs):
        # Residual = +5,000 + -1,500 = +3,500 (allowing the carried -$0.40 sub-cent noise)
        assert diffs.summary.grand_residual == pytest.approx(3500.0, abs=1.0)


# --- Scenario 3: new_stripe_rc -----------------------------------------------

class TestScenario3NewStripeRc:
    def test_period_detected(self, new_stripe):
        assert new_stripe.source.period_label == "2026-03"

    def test_unmapped_stripe_rc_surfaced(self, new_stripe):
        assert "beta_program_credit" in new_stripe.recon.unmapped_stripe_rcs
        assert new_stripe.recon.unmapped_internal_rcs == []

    def test_unmapped_exception_generated(self, new_stripe):
        unmapped = [e for e in new_stripe.exceptions if e.cause == "unmapped_stripe"]
        assert len(unmapped) == 1
        assert unmapped[0].rc == "beta_program_credit"

    def test_residual_unaffected_by_unmapped_rc(self, new_stripe):
        # Unmapped rcs are not summed into the recon — residual matches scenario 1.
        assert abs(new_stripe.summary.grand_residual) < 1.0


# --- Scenario 4: new_internal_rc ---------------------------------------------

class TestScenario4NewInternalRc:
    def test_period_detected(self, new_internal):
        assert new_internal.source.period_label == "2026-04"

    def test_unmapped_internal_rc_surfaced(self, new_internal):
        assert "loyalty_credit" in new_internal.recon.unmapped_internal_rcs
        assert new_internal.recon.unmapped_stripe_rcs == []

    def test_unmapped_exception_generated(self, new_internal):
        unmapped = [e for e in new_internal.exceptions if e.cause == "unmapped_internal"]
        assert len(unmapped) == 1
        assert unmapped[0].rc == "loyalty_credit"

    def test_residual_unaffected_by_unmapped_rc(self, new_internal):
        # Unmapped Internal rcs are not summed into the recon — residual matches scenario 1.
        assert abs(new_internal.summary.grand_residual) < 1.0
